name: directdrop
description: Cross-platform P2P file transfer over the internet using Firebase signaling and WebRTC.
publish_to: 'none'
version: 1.0.30+31

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.6.0
  firebase_auth: ^6.0.0
  firebase_database: ^12.2.0
  flutter_webrtc: ^0.12.4
  file_picker: ^10.3.8
  desktop_drop: ^0.7.1
  path_provider: ^2.1.4
  path: ^1.9.0
  uuid: ^4.5.1
  crypto: ^3.0.5
  qr_flutter: ^4.1.0
  mobile_scanner: ^6.0.2
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  permission_handler: ^11.3.1
  share_plus: ^12.0.2
  open_file: ^3.5.10
  firebase_messaging: ^16.0.2
  flutter_local_notifications: ^18.0.1
  package_info_plus: ^9.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
